### ISSUE TITLE
I wonder if it should be variance or sqrt(variance) here

### ISSUE THREAD

**Issue by alexlyzhov** [izmailovpavel/understandingbdl#14]
https://github.com/izmailovpavel/understandingbdl/blob/5d1004896ea4eb674cff1c2088dc49017a667e9e/swag/posteriors/swag.py#L83

**Comment by izmailovpavel** [comment]
@alexlyzhov thank you, I think you are correct, it seems like this issue was introduced when we refactored the original SWAG code. Do you wanna submit a PR fixing it or should I just fix it?

**Comment by alexlyzhov** [comment]
PR: #15
