### ISSUE TITLE
possible to run swag.py on regression?

### ISSUE THREAD

**Issue by wrkhard** [izmailovpavel/understandingbdl#19]
Hello,

I was curious how many changes are required to train SWAG model on a regression problem using the swag.py, would this require many changes or just a change of args to the arg parser? Thank you!

**Comment by izmailovpavel** [comment]
Hi @wrkhard, sorry for the late reply! SWAG should be generally applicable to regression models without significant modifications. In particular, we applied it to a synthetic regression problem [here]( https://github.com/wjmaddox/drbayes/blob/master/experiments/synthetic_regression/visualizing_uncertainty.ipynb). We also apply it to UCI regression problems [here](https://github.com/wjmaddox/drbayes/tree/master/experiments/uci_exps).
