### ISSUE TITLE
Add license(s)

### ISSUE THREAD

**Issue by kmsquire** [izmailovpavel/understandingbdl#2]
It would be good to add a LICENSE file here so that users understand how the code may be used.  
Additionally, any code which came from other places should include the original license file.

(I'm enjoying reading your paper!)

Cheers!

**Comment by izmailovpavel** [comment]
Thanks @kmsquire, I have added the license for the repo. What is the standard way to specify the original license for code acquired from other repos?

**Comment by kmsquire** [comment]
I'm not sure there's a "standard way", but as long as you do something that reasonably attempts to follow the terms of the license, you should be fine.  I think the [Julia LICENSE file](https://github.com/JuliaLang/julia/blob/master/LICENSE.md) is a good example: they give the license for the code that originated in that repo first, and then for various components which were derived from other sources, they link to the license for that source.

In your case, for the code that was forked from the Subspace Inference GitHub repo, you should probably add the copyright line from that repo to your license file--it's the same license, but the copyright is owned by the people who originally wrote that code.  If you've rewritten most of the code, then you might be off the hook, but you should use your best judgement--it's probably a bad idea to claim copyright on something that someone else wrote! :-)

For the parts which came from the other repo, see the [Apache License 2.0 License](https://github.com/hendrycks/robustness/blob/master/LICENSE) in that repo.  Clause 4 of that license spells out what you're supposed to do.  A link to that license file is probably sufficient for providing the license (Clause 1), but for any parts which you modified, you're supposed to do more (see the license for details).

Hope this helps!

**Comment by izmailovpavel** [comment]
Thank you so much for the tips :) I am on the Subspace Inference repo so I think it will be fine. I modified the LICENSE  file and added a notice to the files adapted from the robustness repo.
