### ISSUE TITLE
SWAG Model

### ISSUE THREAD

**Issue by jgbos** [izmailovpavel/understandingbdl#5]
The if statements have the same line.  Is the first statement supposed to use `swag_model` instead of `model`?

https://github.com/izmailovpavel/understandingbdl/blob/34e21ad1f2c5c752deacb62e5f31d6c9145234ca/experiments/train/run_swag.py#L186

**Comment by izmailovpavel** [comment]
Hi @jgbos, thanks for looking into the code. The implementation is indeed redundant, but there is no error. This implementation was adapted from https://github.com/wjmaddox/swa_gaussian, where I believe we used this if statement at some point.
