### ISSUE TITLE
Pretrained SWAG models

### ISSUE THREAD

**Issue by mohitsharma29** [izmailovpavel/understandingbdl#7]
Hey

Once again, thank you for providing the code for your paper. I was wondering whether you will upload the SWAG models, on which you obtained the results given in the paper.

Thank You

**Comment by izmailovpavel** [comment]
Hey @mohitsharma29, did you need the SWAG checkpoints for any specific architecture from the paper?

**Comment by mohitsharma29** [comment]
Hey 
I trained all models from scratch. Thanks for replying though.
